services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace:cached
      - backend_node_modules:/workspace/backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace:cached
      - frontend_node_modules:/workspace/frontend/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - portfolio-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-portfolio_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-portfolio_password}
      - POSTGRES_DB=${POSTGRES_DB:-portfolio_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

volumes:
  backend_node_modules:
  frontend_node_modules:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge
